### ISSUE TITLE
Introductions

### ISSUE THREAD

**Issue by wehlutyk** [interpretation-experiment/gistr-app#47]
* Home page
  * [x] Add "who"
  * [x] Add incentives
* Play instructions
  * [x] Remove "you can quit", it pushes people to do so
  * [x] ~~Indicate how much time to completion (training + exp)~~ (see #49)
  * [x] ~~Present incentives: end reports + exploration~~ (see #50)
* Play progress
  * [x] ~~Evaluate block progress-bar (avoiding fear that it's too long)~~ (see #51)
  * [x] ~~Evaluate progress-bar with "how much more time it takes"~~ (see #51)
* About
  * [x] Re-add link in home page
  * [x] Only vaguely present the experiment
  * [x] Explain "who", "privacy", incentives
